import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import MyCard from '@/components/myCard'



export default function Home() {
  return (
    <>
      <Head>
        <title>Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <section className={styles.section}>
          <h1 className={styles.title}>Conheça a Lalê!</h1>
          <div className={styles.buttonContainer}>
            <button className={styles.button}>Cardápio</button>
          </div>
        </section>
        <section className={styles.cardsContainer}>
          <MyCard title='Brownie'>
            <span>
              <ul>
                <li>Delicioso</li>
                <li>Sem glúten</li>
                <li>Feito com muito amor</li>
              </ul>
            </span>
          </MyCard>
          
        </section>
        
      </main>
    </>
  )
}

